import { describe, it, expect } from 'vitest'
import { generateReport } from '../../../src/export/report-generator'
import type { AnalysisResult, SignalMatch, FixStep } from '../../../src/types/global'

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

const FULL_SESSION_ID = 'abcdef12-3456-7890-abcd-ef1234567890'
const SESSION_ID_SHORT = '34567890' // last 8 chars

const baseSession = {
  appName: 'Valorant',
  issueType: 'crash',
  sessionId: FULL_SESSION_ID,
  startedAt: '2026-05-12T14:35:00.000Z',
}

const signal1: SignalMatch = {
  type: 'event',
  technical: 'Event 153 — nvlddmkm',
  description: 'GPU driver reset (TDR) occurred',
  seconds_before_marker: 12,
}

const signal2: SignalMatch = {
  type: 'metric',
  technical: 'GPU utilization 94%',
  description: 'High GPU load in incident window',
  seconds_before_marker: 10,
}

const fix1: FixStep = {
  order: 1,
  title: 'Update GPU driver',
  detail: 'Open Device Manager → Display Adapters → update GPU driver',
  link: 'https://example.com/gpu-driver',
}

const fix2: FixStep = {
  order: 2,
  title: 'Roll back driver if recently updated',
  detail: 'If recently updated, roll back driver to previous version',
}

const diagnosedResult: AnalysisResult = {
  id: 'result-001',
  session_id: FULL_SESSION_ID,
  outcome: 'diagnosed',
  primary_rule_pack_id: 'gpu-driver',
  primary_confidence: 'HIGH',
  primary_cause_name: 'GPU Driver Instability / TDR',
  primary_output_text:
    'A GPU driver reset was detected 12 seconds before the crash. GPU utilization was at 94% at the time. This strongly indicates GPU driver instability.',
  secondary_results: [],
  all_signals_found: [signal1, signal2],
  fix_recommendations: [fix2, fix1], // intentionally out of order to test sorting
  inconclusive_reason: null,
  created_at: '2026-05-12T14:36:00.000Z',
}

const inconclusiveResult: AnalysisResult = {
  id: 'result-002',
  session_id: FULL_SESSION_ID,
  outcome: 'inconclusive',
  primary_rule_pack_id: null,
  primary_confidence: null,
  primary_cause_name: null,
  primary_output_text: null,
  secondary_results: [],
  all_signals_found: [],
  fix_recommendations: [],
  inconclusive_reason: 'No rule pack reached MEDIUM confidence or above.',
  created_at: '2026-05-12T14:36:00.000Z',
}

const mediumConfidenceResult: AnalysisResult = {
  ...diagnosedResult,
  id: 'result-003',
  primary_confidence: 'MEDIUM',
  primary_cause_name: 'Overlay Conflict',
  primary_output_text:
    'A silent crash was detected with overlay processes active. This is consistent with an overlay conflict, though other causes cannot be ruled out.',
}

const emptySignalsResult: AnalysisResult = {
  ...diagnosedResult,
  id: 'result-004',
  all_signals_found: [],
  fix_recommendations: [],
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('generateReport', () => {
  describe('markdown structure', () => {
    it('includes all required section headers', () => {
      const { markdown } = generateReport(diagnosedResult, baseSession)
      expect(markdown).toContain('# Black Box Session Report')
      expect(markdown).toContain('## Diagnosis')
      expect(markdown).toContain('## Evidence Found')
      expect(markdown).toContain('## Fix Recommendations')
      expect(markdown).toContain('## All Signals Detected')
      expect(markdown).toContain('Generated by Black Box v1.0.0')
    })

    it('includes session metadata fields', () => {
      const { markdown } = generateReport(diagnosedResult, baseSession)
      expect(markdown).toContain('Issue Type: crash')
      expect(markdown).toContain('App / Game: Valorant')
    })

    it('includes the date formatted from startedAt', () => {
      const { markdown } = generateReport(diagnosedResult, baseSession)
      // Should contain the year 2026 at minimum
      expect(markdown).toMatch(/Date:.*2026/)
    })

    it('ends with a horizontal rule separator before the footer', () => {
      const { markdown } = generateReport(diagnosedResult, baseSession)
      expect(markdown).toContain('---')
    })
  })

  describe('session ID privacy', () => {
    it('never includes the full session ID in the markdown', () => {
      const { markdown } = generateReport(diagnosedResult, baseSession)
      expect(markdown).not.toContain(FULL_SESSION_ID)
    })

    it('includes only the last 8 characters of the session ID', () => {
      const { markdown, sessionIdShort } = generateReport(diagnosedResult, baseSession)
      expect(sessionIdShort).toBe(SESSION_ID_SHORT)
      expect(markdown).toContain(`Session ID: ${SESSION_ID_SHORT}`)
    })

    it('returns the correct sessionIdShort in the result object', () => {
      const { sessionIdShort } = generateReport(diagnosedResult, baseSession)
      expect(sessionIdShort).toHaveLength(8)
      expect(sessionIdShort).toBe(SESSION_ID_SHORT)
    })

    it('never includes the full session ID even when it appears in result fields', () => {
      // The AnalysisResult contains session_id — confirm it is not leaked
      const { markdown } = generateReport(diagnosedResult, baseSession)
      // Full UUID should not appear anywhere
      const uuidPattern = /abcdef12-3456-7890-abcd-ef1234567890/
      expect(markdown).not.toMatch(uuidPattern)
    })
  })

  describe('HIGH confidence diagnosed session', () => {
    it('includes Confidence: HIGH', () => {
      const { markdown } = generateReport(diagnosedResult, baseSession)
      expect(markdown).toContain('Confidence: HIGH')
    })

    it('includes the primary cause name', () => {
      const { markdown } = generateReport(diagnosedResult, baseSession)
      expect(markdown).toContain('Most Likely Cause: GPU Driver Instability / TDR')
    })

    it('includes the primary output text', () => {
      const { markdown } = generateReport(diagnosedResult, baseSession)
      expect(markdown).toContain('GPU driver reset was detected')
    })

    it('lists all detected signals', () => {
      const { markdown } = generateReport(diagnosedResult, baseSession)
      expect(markdown).toContain('Event 153 — nvlddmkm')
      expect(markdown).toContain('GPU driver reset (TDR) occurred')
      expect(markdown).toContain('GPU utilization 94%')
    })

    it('includes relative timing for signals', () => {
      const { markdown } = generateReport(diagnosedResult, baseSession)
      expect(markdown).toContain('12s before crash')
      expect(markdown).toContain('10s before crash')
    })
  })

  describe('MEDIUM confidence diagnosed session', () => {
    it('includes Confidence: MEDIUM', () => {
      const { markdown } = generateReport(mediumConfidenceResult, baseSession)
      expect(markdown).toContain('Confidence: MEDIUM')
    })

    it('includes the correct cause name', () => {
      const { markdown } = generateReport(mediumConfidenceResult, baseSession)
      expect(markdown).toContain('Most Likely Cause: Overlay Conflict')
    })
  })

  describe('inconclusive session', () => {
    it('includes Confidence: INCONCLUSIVE', () => {
      const { markdown } = generateReport(inconclusiveResult, baseSession)
      expect(markdown).toContain('Confidence: INCONCLUSIVE')
    })

    it('includes Most Likely Cause: Inconclusive', () => {
      const { markdown } = generateReport(inconclusiveResult, baseSession)
      expect(markdown).toContain('Most Likely Cause: Inconclusive')
    })

    it('has the no-signals message in evidence section', () => {
      const { markdown } = generateReport(inconclusiveResult, baseSession)
      expect(markdown).toContain('No signals detected')
    })

    it('has the no-fix-recommendations message', () => {
      const { markdown } = generateReport(inconclusiveResult, baseSession)
      expect(markdown).toContain('No specific fix recommendations')
    })

    it('still includes all required section headers', () => {
      const { markdown } = generateReport(inconclusiveResult, baseSession)
      expect(markdown).toContain('## Diagnosis')
      expect(markdown).toContain('## Evidence Found')
      expect(markdown).toContain('## Fix Recommendations')
      expect(markdown).toContain('## All Signals Detected')
    })
  })

  describe('fix recommendations ordering', () => {
    it('sorts fix steps by order number regardless of input order', () => {
      const { markdown } = generateReport(diagnosedResult, baseSession)
      // fix2 has order:2, fix1 has order:1 — they were added out of order in the fixture
      // Expect "1." to appear before "2."
      const idx1 = markdown.indexOf('1. **Update GPU driver**')
      const idx2 = markdown.indexOf('2. **Roll back driver')
      expect(idx1).toBeGreaterThan(-1)
      expect(idx2).toBeGreaterThan(-1)
      expect(idx1).toBeLessThan(idx2)
    })

    it('includes step title and detail in output', () => {
      const { markdown } = generateReport(diagnosedResult, baseSession)
      expect(markdown).toContain('Update GPU driver')
      expect(markdown).toContain('Open Device Manager')
    })

    it('includes optional link when present', () => {
      const { markdown } = generateReport(diagnosedResult, baseSession)
      expect(markdown).toContain('https://example.com/gpu-driver')
    })

    it('does not crash when fix_recommendations is empty', () => {
      expect(() => generateReport(emptySignalsResult, baseSession)).not.toThrow()
      const { markdown } = generateReport(emptySignalsResult, baseSession)
      expect(markdown).toContain('No specific fix recommendations')
    })
  })

  describe('empty evidence list', () => {
    it('does not crash when all_signals_found is empty', () => {
      expect(() => generateReport(emptySignalsResult, baseSession)).not.toThrow()
    })

    it('shows empty state message in evidence section', () => {
      const { markdown } = generateReport(emptySignalsResult, baseSession)
      expect(markdown).toContain('No evidence signals were captured')
    })
  })

  describe('filename generation', () => {
    it('generates a filename with the correct format', () => {
      const { filename } = generateReport(diagnosedResult, baseSession)
      // Format: blackbox-report-YYYY-MM-DD-[shortId].md
      expect(filename).toMatch(/^blackbox-report-\d{4}-\d{2}-\d{2}-[a-z0-9]{8}\.md$/)
    })

    it('filename contains the session ID short form', () => {
      const { filename, sessionIdShort } = generateReport(diagnosedResult, baseSession)
      expect(filename).toContain(sessionIdShort)
    })

    it('filename contains the date from startedAt', () => {
      const { filename } = generateReport(diagnosedResult, baseSession)
      expect(filename).toContain('2026-05-12')
    })

    it('ends with .md extension', () => {
      const { filename } = generateReport(diagnosedResult, baseSession)
      expect(filename).toMatch(/\.md$/)
    })
  })

  describe('signal relative time formatting', () => {
    it('handles signal exactly at crash point', () => {
      const zeroSignal: SignalMatch = {
        type: 'event',
        technical: 'Event 1002',
        description: 'Application hang at crash point',
        seconds_before_marker: 0,
      }
      const result: AnalysisResult = { ...diagnosedResult, all_signals_found: [zeroSignal] }
      const { markdown } = generateReport(result, baseSession)
      expect(markdown).toContain('at crash point')
    })

    it('handles signal after the crash point (negative seconds_before_marker)', () => {
      const afterSignal: SignalMatch = {
        type: 'event',
        technical: 'Event 1001',
        description: 'Windows Error Reporting logged',
        seconds_before_marker: -30,
      }
      const result: AnalysisResult = { ...diagnosedResult, all_signals_found: [afterSignal] }
      const { markdown } = generateReport(result, baseSession)
      expect(markdown).toContain('30s after crash')
    })
  })
})
