/**
 * report-generator.ts
 *
 * Pure function — no Node.js-only or Electron imports.
 * Safe to import from both the renderer process and the main process.
 *
 * Generates a plain-text markdown session report from an AnalysisResult.
 * Privacy rule: the full session ID is NEVER included — only the last 8 characters.
 */

import type { AnalysisResult, SignalMatch, FixStep } from '../types/global'

export interface ReportSession {
  appName: string
  issueType: string
  sessionId: string
  startedAt: string
}

export interface GeneratedReport {
  markdown: string
  filename: string
  sessionIdShort: string
}

/** Format an ISO timestamp into a human-readable date string. */
function formatDate(isoString: string): string {
  const d = new Date(isoString)
  if (isNaN(d.getTime())) return isoString
  // e.g. "May 12, 2026 at 14:35 UTC"
  return d.toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    timeZoneName: 'short',
    hour12: false,
  })
}

/** Format a date as YYYY-MM-DD for use in the filename. */
function formatDateForFilename(isoString: string): string {
  const d = new Date(isoString)
  if (isNaN(d.getTime())) return 'unknown'
  const year = d.getUTCFullYear()
  const month = String(d.getUTCMonth() + 1).padStart(2, '0')
  const day = String(d.getUTCDate()).padStart(2, '0')
  return `${year}-${month}-${day}`
}

/** Format seconds-before-marker into a human-readable relative string. */
function formatRelativeTime(secondsBefore: number): string {
  if (secondsBefore === 0) return 'at crash point'
  const abs = Math.abs(secondsBefore)
  if (secondsBefore > 0) return `${abs}s before crash`
  return `${abs}s after crash`
}

/** Render a single SignalMatch as a markdown block. */
function renderSignal(signal: SignalMatch): string {
  const relTime = formatRelativeTime(signal.seconds_before_marker)
  return `- \`${signal.technical}\` — ${signal.description} (${relTime})`
}

/** Render fix recommendations as a numbered list. */
function renderFixSteps(steps: FixStep[]): string {
  if (steps.length === 0) return '_No specific fix recommendations available._'
  const sorted = [...steps].sort((a, b) => a.order - b.order)
  return sorted
    .map((step) => {
      const link = step.link != null ? `\n   Reference: ${step.link}` : ''
      return `${step.order}. **${step.title}**\n   ${step.detail}${link}`
    })
    .join('\n\n')
}

/** Render all detected signals as a flat technical list for forum posting. */
function renderAllSignals(signals: SignalMatch[]): string {
  if (signals.length === 0) return '_No signals detected during this session._'
  return signals.map(renderSignal).join('\n')
}

export function generateReport(
  result: AnalysisResult,
  session: ReportSession,
): GeneratedReport {
  const sessionIdShort = session.sessionId.slice(-8)
  const dateFormatted = formatDate(session.startedAt)
  const dateForFilename = formatDateForFilename(session.startedAt)
  const filename = `blackbox-report-${dateForFilename}-${sessionIdShort}.md`

  // Determine confidence and cause display values
  const confidenceLabel: string =
    result.outcome === 'inconclusive' || result.primary_confidence == null
      ? 'INCONCLUSIVE'
      : result.primary_confidence

  const causeName: string =
    result.outcome === 'diagnosed' && result.primary_cause_name != null
      ? result.primary_cause_name
      : 'Inconclusive'

  // Evidence section
  let evidenceSection: string
  if (result.all_signals_found.length === 0) {
    evidenceSection = '_No evidence signals were captured during this session._'
  } else {
    // Show only signals found during the incident / baseline windows (all of them)
    evidenceSection = result.all_signals_found.map(renderSignal).join('\n')
  }

  // Fix recommendations section
  const fixSection = renderFixSteps(result.fix_recommendations)

  // All signals section (same data, shown explicitly for forum sharing)
  const allSignalsSection = renderAllSignals(result.all_signals_found)

  const markdown = [
    `# Black Box Session Report`,
    `Date: ${dateFormatted}`,
    `Issue Type: ${session.issueType}`,
    `App / Game: ${session.appName}`,
    `Session ID: ${sessionIdShort}`,
    ``,
    `## Diagnosis`,
    `Confidence: ${confidenceLabel}`,
    `Most Likely Cause: ${causeName}`,
    result.primary_output_text != null ? `\n${result.primary_output_text}` : '',
    ``,
    `## Evidence Found`,
    evidenceSection,
    ``,
    `## Fix Recommendations`,
    fixSection,
    ``,
    `## All Signals Detected`,
    allSignalsSection,
    ``,
    `---`,
    `Generated by Black Box v1.0.0`,
  ]
    .filter((line) => line !== null)
    .join('\n')

  return { markdown, filename, sessionIdShort }
}
